export default [
    {   
        id_restaurante : "1",
        title:'Chilis',
        description:'“Aquí vives más cada momento”',
        image: require("../../assets/logos/chilis.png"),
        logo : require("../../assets/logos/chillis-logo.png"),
        comida : "Hamburguesa",
        precio : "6",
        direccion : "Calle Verde 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "2",
        title:'Fridays',
        description:'Come for the food, stay for the fun. · In Here, Its Always Friday.',
        image: require("../../assets/logos/fridays.jpeg"),
        logo : require("../../assets/logos/fridayslogo.png"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle Azul 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "3",
        title:'Pardos Chicken',
        description:'Siente el sabor peruano!! Es nuestro slogan hace años, no solo nos referimos a la comida. Sino a nuestra música, moda, arte, orfebrería, vida y mucho más.',
        image: require("../../assets/logos/Pardos_surco.jpeg"),
        logo : require("../../assets/logos/Logo_Pardos.jpeg"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle Verde 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "4",
        title:'Jhonny Rockets',
        description:'Hamburguesas, Shakes, papas fritas y una Experiencia de entretención',
        image: require("../../assets/logos/jhonyrockets.jpeg"),
        logo : require("../../assets/logos/logojohnny.png"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle Violeta 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "5",
        title:'Don Belisario',
        description:'Amamos el Pollo a la Brasa.',
        image: require("../../assets/logos/don-belisario-1.jpeg"),
        logo : require("../../assets/logos/donbelisariologo.png"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle amarilla 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "6",
        title:'Oliver',
        description:'A un paso de la comida, a un paso de la vida.',
        image: require("../../assets/logos/oliverjockey.jpeg"),
        logo : require("../../assets/logos/logoliver.png"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle rojo 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "7",
        title:'Madam Tusan',
        description:'"La gente disfruta tenerte cerca. Aprecia esto"',
        image: require("../../assets/logos/madamtusan.jpg"),
        logo : require("../../assets/logos/logomadamtusan.jpg"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle negro 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "8",
        title:'Siete Sopas',
        description:'Sopas disitntas , 7 dias de la semana',
        image: require("../../assets/logos/sietesopas.jpg"),
        logo : require("../../assets/logos/sietesopaslogo.jpg"),
        comida : "Sopas",
        precio : "10",
        direccion : "Calle marron 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "9",
        title:'La nevera Fit',
        description:'Fit, Fit, Fit',
        image: require("../../assets/logos/laneverafit.jpg"),
        logo : require("../../assets/logos/laneverafitlogo.jpg"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle Celeste 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "10",
        title:'Mediterraneo',
        description:'mediterraneo es una empresa de comida rápida, con una amplia variedad de sabores y sabores de comida mediterránea.',
        image: require("../../assets/logos/mediterraneo.jpeg"),
        logo : require("../../assets/logos/mediterraneologo.jpeg"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle Plomo 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "11",
        title:'Mr Shao',
        description:'我偶尔看书我偶尔看书 我偶尔看书',
        image: require("../../assets/logos/mrshao.jpg"),
        logo : require("../../assets/logos/mrshaologo.jpg"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle naranja 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "12",
        title:'Rustica',
        description:'Rustica a tu alcance',
        image: require("../../assets/logos/rustica.jpeg"),
        logo : require("../../assets/logos/rusticalogo.png"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle blanco 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "13",
        title:'La Lucha',
        description:'Lucha para el bien de tu familia',
        image: require("../../assets/logos/lalucha.jpg"),
        logo : require("../../assets/logos/laluchalogo.jpg"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle rosado 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "14",
        title:'Papa Jonhns',
        description:'Pizza y hamburguesa',
        image: require("../../assets/logos/papajohns.jpeg"),
        logo : require("../../assets/logos/papajohnslogo.png"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle Dorado 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "15",
        title:'La Trattoria',
        description:'Trattoria abcdefghi',
        image: require("../../assets/logos/latrattoria.jpg"),
        logo : require("../../assets/logos/latrattorialogo.jpg"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle Plateado 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },
    {
        id_restaurante : "16",
        title:'Mr Sushi',
        description:'Sushi para todos',
        image: require("../../assets/logos/mr-sushi-fachada.jpeg"),
        logo : require("../../assets/logos/mrsushilogo.jpeg"),
        comida : "Hamburguesa",
        precio : "10",
        direccion : "Calle Invisible 123",
        horario : "Lunes a Viernes de 10:00 a 22:00",
        telefono : "123456789",
    },


    
]